import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import type { ArbitrationRewardPool, ArbitrationRewardView, CollaborationIssue } from '../../../shared/collaboration';
import { api } from '../services/api';
import { useAppStore } from '../store/useAppStore';
import { useAuth } from '../auth/AuthProvider';
import { isWeb3Payment } from '../utils/payments';
import { CollaborationPanel } from './CollaborationPanel';
const workLabels = {withdrawn:'已回避 · 不扣履职信誉，预算已释放',accepted:'已接案 · 待履职',submitted:'履职已提交 · 待审核',approved:'履职审核通过 · 报酬已记账',rejected:'未通过履职审核'};
export function ArbitrationCollaboration({disputeId,revision}:{disputeId:string;revision?:string}) {
  const profile=useAppStore(s=>s.profile); const [data,setData]=useState<ArbitrationRewardView|null>(null);
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [body,setBody]=useState('');const [report,setReport]=useState('');const [evidence,setEvidence]=useState<string[]>([]);const [reasons,setReasons]=useState<Record<string,string>>({});
  const refresh=useCallback(async()=>setData(await api.getArbitrationCollaboration(disputeId)),[disputeId]);
  useEffect(()=>{let active=true;setData(null);setBody('');setReport('');setEvidence([]);setError('');void api.getArbitrationCollaboration(disputeId).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[disputeId,revision]);
  const act=async(action:string,payload:unknown)=>{setBusy(true);setError('');try{await api.arbitrationCollaborationAction(disputeId,action,payload);await refresh();setBody('');}catch(e){setError(e instanceof Error?e.message:'提交失败。');}finally{setBusy(false);}};
  return <section className="panel space-y-4 p-5"><h2 className="font-semibold">双方陈述与仲裁履职</h2>{error&&<p className="text-sm text-danger" role="alert">{error}</p>}{!data&&!error&&<p className="text-xs text-muted">加载案件协作记录…</p>}{data&&<>
    <p className="text-xs leading-5 text-muted">双方可以补充答辩。补充材料独立保留时间记录，案件创建时的冻结证据不被覆盖。</p>
    {data.linkedIssues.map(i=><article key={i.id} className="rounded-xl bg-canvas p-3"><p className="text-sm font-semibold">关联协调申请：{i.title}</p><p className="mt-2 whitespace-pre-wrap text-sm">{i.body}</p><p className="mt-2 text-xs text-muted">{i.id} · {new Date(i.createdAt).toLocaleString('zh-CN',{hour12:false})}</p></article>)}
    {data.messages.map(m=><article className="rounded-xl bg-canvas p-3" key={m.id}><p className="text-xs text-muted">{m.authorId===profile?.id?'你的陈述':'案件当事方'} · {new Date(m.createdAt).toLocaleString('zh-CN',{hour12:false})}</p><p className="mt-2 whitespace-pre-wrap text-sm">{m.body}</p>{m.evidence.map(e=><a href={e.uri} className="mr-3 text-xs text-cyan" target="_blank" rel="noreferrer" key={e.uri}>{e.label}</a>)}</article>)}
    {data.canRespond&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();void act('collaboration',{body});}}><label className="block"><span className="field-label">事实说明、证据链接及对对方材料的回应</span><textarea className="field min-h-24" required minLength={5} maxLength={2000} value={body} onChange={e=>setBody(e.target.value)}/></label><button className="btn-secondary" disabled={busy}>提交案件陈述</button></form>}
    <div className="border-t border-line pt-4"><h3 className="font-semibold">固定审案报酬</h3><p className="mt-2 text-xs text-muted">你的仲裁履历：接案 {data.reputation.accepted} · 已提交 {data.reputation.submitted} · 审核通过 {data.reputation.approved} · 未通过 {data.reputation.rejected}</p><p className="mt-2 text-xs leading-5 text-muted">接案时预留预算；按时投票并提交至少 80 字、引用证据的审案说明，由无利益冲突的管理员审核履职。支持退款和反对退款同酬，不以多数票或资金执行作为发放条件。预算是报酬承诺，实际领取须等待奖励周期在链上发布。</p>
    {data.pools.map(pool=><div className="mt-3 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-canvas p-3" key={pool.id}><p className="text-xs">每轮 {pool.feeMicros/1e6} PM · 可预留 {(pool.budgetMicros-pool.reservedMicros)/1e6} PM</p>{data.canAccept&&<button className="btn-primary" disabled={busy||pool.reservedMicros+pool.feeMicros>pool.budgetMicros} onClick={()=>void act('reward-work/accept',{poolId:pool.id})}>接受审案与报酬</button>}</div>)}{data.pools.length===0&&<p className="mt-3 text-xs text-muted">当前没有已配置的固定报酬预算；普通 DAO 投票仍可参与。</p>}
    {data.work.map(work=><article className="mt-3 space-y-3 rounded-xl border border-line p-4" key={work.id}><p className="text-sm font-semibold">{work.userId===profile?.id?'你的履职':`委员 ${work.userId}`} · {work.feeMicros/1e6} PM</p><p className="text-xs text-muted">{workLabels[work.status]} · {work.proposalId}</p>{work.report&&<p className="whitespace-pre-wrap text-sm">{work.report}</p>}{work.evidence.length>0&&<p className="break-all text-xs text-muted">引用：{work.evidence.join('；')}</p>}{work.reviewReason&&<p className="text-xs">审核理由：{work.reviewReason}</p>}{work.status==='approved'&&<Link className="text-xs text-cyan" to="/yd-finance">前往 PM 奖励中心查看发布与领取状态 →</Link>}
      {work.userId===profile?.id&&work.status==='accepted'&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();void act('reward-work/submit',{workId:work.id,report,evidence});}}><label className="block"><span className="field-label">审案说明：证据、判断依据及争议点</span><textarea className="field min-h-28" required minLength={80} maxLength={4000} value={report} onChange={e=>setReport(e.target.value)}/></label><fieldset className="space-y-2"><legend className="field-label">已审阅的证据</legend>{data.evidenceOptions.map(v=><label key={v} className="flex gap-2 break-all text-xs"><input type="checkbox" checked={evidence.includes(v)} onChange={e=>setEvidence(e.target.checked?[...evidence,v]:evidence.filter(x=>x!==v))}/>{v}</label>)}</fieldset><div className="flex flex-wrap gap-2"><button className="btn-secondary" disabled={busy||!evidence.length}>投票后提交履职</button><button type="button" className="btn-secondary" disabled={busy||report.trim().length<12} onClick={()=>void act('reward-work/withdraw',{workId:work.id,reason:report})}>以说明申请回避（仅投票前）</button></div></form>}
      {profile?.role==='admin'&&work.status==='submitted'&&work.userId!==profile.id&&<div className="space-y-2"><textarea className="field" aria-label="履职审核理由" placeholder="按证据审阅与理由完整性审核，不能以是否支持多数派为依据；至少 12 字。" minLength={12} maxLength={2000} value={reasons[work.id]??''} onChange={e=>setReasons({...reasons,[work.id]:e.target.value})}/><div className="flex gap-2">{(['approve','reject'] as const).map(action=><button key={action} className="btn-secondary" disabled={busy||(reasons[work.id]?.trim().length??0)<12} onClick={()=>void act(`reward-work/${action}`,{workId:work.id,reason:reasons[work.id]})}>{action==='approve'?'通过履职审核':'退回并说明原因'}</button>)}</div></div>}
    </article>)}
    </div>
  </>}</section>;
}
export function ArbitrationOperations() {
  const profile=useAppStore(s=>s.profile); const [issues,setIssues]=useState<CollaborationIssue[]>([]); const [pools,setPools]=useState<ArbitrationRewardPool[]>([]);
  const [selected,setSelected]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const [budget,setBudget]=useState('100');const [fee,setFee]=useState('5');const [startsAt,setStartsAt]=useState(new Date().toISOString().slice(0,10));const [endsAt,setEndsAt]=useState(new Date(Date.now()+30*86400000).toISOString().slice(0,10));
  const {freezeEscrow}=useAuth();const loadMissionDetail=useAppStore(s=>s.loadMissionDetail);const bootstrap=useAppStore(s=>s.hydratePrivate);
  const refresh=useCallback(async()=>{const [i,p]=await Promise.all([api.listEscalatedIssues(),api.listArbitrationRewardPools()]);setIssues(i);setPools(p);},[]);
  useEffect(()=>{if(profile?.role==='admin')void refresh().catch(e=>setError(e.message));},[profile?.role,refresh]);
  if(profile?.role!=='admin')return null;
  const createPool=async()=>{setBusy(true);setError('');try{await api.createArbitrationRewardPool({startsAt:new Date(startsAt).toISOString(),endsAt:new Date(endsAt).toISOString(),budgetMicros:Math.round(Number(budget)*1e6),feeMicros:Math.round(Number(fee)*1e6)});await refresh();}catch(e){setError(e instanceof Error?e.message:'预算保存失败。');}finally{setBusy(false);}};
  const openFundsCase=async(issue:CollaborationIssue)=>{setBusy(true);setError('');try{const detail=await api.getMission(issue.missionId);if(!['running','paused','review'].includes(detail.mission.status)||detail.escrow?.status!=='held')throw new Error('当前任务没有可冻结的托管，请在协作区记录处理结论。');const tx=isWeb3Payment(detail.mission.paymentMethod)?await freezeEscrow(issue.missionId):null;await api.createDispute(issue.missionId,`双方协商未达成一致，申请对任务托管进行资金仲裁。申请编号 ${issue.id}。`,tx,issue.id);await loadMissionDetail(issue.missionId);await bootstrap();await refresh();}catch(e){setError(e instanceof Error?e.message:'资金案件创建失败。');}finally{setBusy(false);}};
  return <section className="panel space-y-4 p-5"><h2 className="font-semibold">双边协调申请与仲裁预算</h2>{error&&<p role="alert" className="text-sm text-danger">{error}</p>}{issues.length===0?<p className="text-xs text-muted">暂无待处理的双边协调申请。</p>:issues.map(issue=><article className="rounded-xl border border-line p-3" key={issue.id}><p className="text-sm font-semibold">{issue.title}</p><p className="mt-1 text-xs text-muted">{issue.missionId} · {issue.disputeId?'已关联资金案件':'待协调审核'}</p><div className="mt-3 flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>setSelected(selected===issue.missionId?'':issue.missionId)}>查看双方材料 / 处理</button>{!issue.disputeId&&<details><summary className="btn-secondary cursor-pointer">转为资金仲裁</summary><p className="my-2 max-w-md text-xs text-muted">会冻结整笔任务托管并进入 DAO 裁决；请确认涉及资金争议，且不能通过普通协调解决。链上任务还需钱包核验。</p><button className="btn-primary" disabled={busy} onClick={()=>void openFundsCase(issue)}>确认建立资金案件并冻结</button></details>}</div></article>)}{selected&&<CollaborationPanel key={selected} missionId={selected}/>}
    <details className="rounded-xl border border-line p-4"><summary className="cursor-pointer text-sm font-semibold">配置固定审案报酬</summary><p className="mt-3 text-xs leading-5 text-muted">同一时间只启用一个预算周期；接案预留后不可修改报酬。此处保存预算承诺，实际发放仍须在 PM 奖励中心创建并发布资金充足的奖励周期。</p><div className="mt-3 space-y-2">{pools.map(p=><p key={p.id} className="text-xs">{p.startsAt.slice(0,10)}—{p.endsAt.slice(0,10)} · 每轮 {p.feeMicros/1e6} PM · 已预留 {p.reservedMicros/1e6} / {p.budgetMicros/1e6} PM</p>)}</div><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void createPool();}}><label><span className="field-label">开始日期（UTC）</span><input className="field" type="date" required value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label><label><span className="field-label">结束日期（不含，UTC）</span><input className="field" type="date" required value={endsAt} onChange={e=>setEndsAt(e.target.value)}/></label><label><span className="field-label">预算上限 PM</span><input className="field" type="number" min="0.000001" step="0.000001" max="1000000" required value={budget} onChange={e=>setBudget(e.target.value)}/></label><label><span className="field-label">每轮审案 PM</span><input className="field" type="number" min="0.000001" step="0.000001" required value={fee} onChange={e=>setFee(e.target.value)}/></label><button className="btn-primary" disabled={busy}>保存周期预算</button></form></details>
  </section>;
}
