import { useCallback, useEffect, useRef, useState } from 'react';
import { LoaderCircle, MessageSquareText, RefreshCw } from 'lucide-react';
import type { CollaborationView, IssueCategory } from '../../../shared/collaboration';
import { api } from '../services/api';
import { useAppStore } from '../store/useAppStore';
const categories: Record<IssueCategory, string> = { delivery:'交付问题',scope_change:'需求变更 / 超范围',missing_material:'资料缺失',acceptance_delay:'验收阻塞',review_appeal:'评价复核',platform_bug:'平台问题' };
const statuses = {open:'协商中',escalated:'已申请协调 / 仲裁审核',resolved:'已解决'};
const requesterLabels = ['交付质量','需求符合度','沟通质量','准时程度','再次合作意愿'];
const developerLabels = ['需求清晰度','资料准备','响应效率','按约验收','再次合作意愿'];
export function CollaborationPanel({ missionId }: { missionId:string }) {
  const profile = useAppStore(s=>s.profile);
  const [data,setData] = useState<CollaborationView|null>(null);
  const [error,setError] = useState(''); const [busy,setBusy] = useState(false);
  const [developerId,setDeveloperId] = useState('');
  const [selectedStageIds,setSelectedStageIds] = useState<string[]|null>(null);
  const issueFormRef=useRef<HTMLDetailsElement>(null);
  const [title,setTitle]=useState(''); const [body,setBody]=useState(''); const [category,setCategory]=useState<IssueCategory>('delivery');
  const [ratings,setRatings]=useState([5,5,5,5,5]); const [comment,setComment]=useState('');
  const [responses,setResponses]=useState<Record<string,string>>({});
  const refresh=useCallback(async()=>{ const next=await api.getCollaboration(missionId); setData(next); setDeveloperId(value=>next.pairs.some(p=>p.developerId===value)?value:next.pairs[0]?.developerId??''); },[missionId]);
  useEffect(()=>{let active=true;setData(null);setError('');setResponses({}); void api.getCollaboration(missionId).then(next=>{if(active){setData(next);setDeveloperId(next.pairs[0]?.developerId??'');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[missionId]);
  const act=async(action:string,payload:unknown,done?:()=>void)=>{setBusy(true);setError('');try{await api.collaborationAction(missionId,action,payload);await refresh();done?.();}catch(e){setError(e instanceof Error?e.message:'提交失败，请重试。');}finally{setBusy(false);}};
  const pair=data?.pairs.find(p=>p.developerId===developerId);
  const issueStageIds=selectedStageIds??pair?.stageIds??[];
  return <section className="panel space-y-5 p-5 md:p-6" aria-label="双边协作与反馈">
    <div className="flex items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 font-semibold"><MessageSquareText size={18}/>双边协作与反馈</h2><p className="mt-1 text-xs leading-5 text-muted">问题记录仅合作双方与管理员可见；转入仲裁后委员会可读取相关材料。协商 48 小时后可申请协调；申请本身不冻结资金。</p></div><button type="button" className="btn-secondary" disabled={busy} aria-label="刷新协作记录" onClick={()=>void refresh().catch(e=>setError(e.message))}><RefreshCw size={14}/></button></div>
    {error&&<p role="alert" className="text-sm text-danger">{error}</p>}
    {!data&&!error&&<p className="text-sm text-muted">正在加载协作记录…</p>}
    {data&&<>
      <p className="rounded-xl bg-canvas p-3 text-xs text-muted">任务方合作信誉：{data.requesterReputation.score??'暂无评分'}{data.requesterReputation.score!==null?' / 5':''} · {data.requesterReputation.count} 次有效合作评价 · {data.requesterReputation.confidence==='low'?'样本较少，谨慎参考':data.requesterReputation.confidence==='medium'?'中等样本':'充足样本'}</p>
      {data.pairs.length>0&&<label className="block"><span className="field-label">合作开发者及交付范围</span><select className="field" value={developerId} onChange={e=>{setDeveloperId(e.target.value);setSelectedStageIds(null);setRatings([5,5,5,5,5]);setComment('');}}>{data.pairs.map(p=><option value={p.developerId} key={p.developerId}>{p.name} · {p.stageNames.join(' / ')}</option>)}</select></label>}
      {pair&&<details ref={issueFormRef} className="rounded-xl border border-line p-4"><summary className="cursor-pointer text-sm font-semibold">提交问题 / 申请评价复核</summary><form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();void act('issues',{developerId,stageIds:issueStageIds,category,title,body},()=>{setTitle('');setBody('');if(issueFormRef.current)issueFormRef.current.open=false;});}}><label className="block"><span className="field-label">问题类型</span><select className="field" value={category} onChange={e=>setCategory(e.target.value as IssueCategory)}>{Object.entries(categories).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><fieldset className="space-y-2"><legend className="field-label">涉及节点</legend>{pair.stageIds.map((stageId,index)=><label className="flex items-center gap-2 text-xs" key={stageId}><input type="checkbox" checked={issueStageIds.includes(stageId)} onChange={e=>setSelectedStageIds(e.target.checked?[...issueStageIds,stageId]:issueStageIds.filter(id=>id!==stageId))}/>{pair.stageNames[index]}</label>)}</fieldset><label className="block"><span className="field-label">标题</span><input className="field" required minLength={5} maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="block"><span className="field-label">事实、涉及节点和期望处理方式</span><textarea className="field min-h-24" required minLength={5} maxLength={2000} value={body} onChange={e=>setBody(e.target.value)}/></label><button className="btn-primary" disabled={busy||!issueStageIds.length} type="submit">提交问题</button></form></details>}
      {data.issues.length===0&&<p className="text-xs text-muted">暂无协作问题。</p>}
      {data.issues.map(issue=><article key={issue.id} className="space-y-3 rounded-xl border border-line p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{issue.title}</h3><span className="text-xs text-muted">{categories[issue.category]} · {statuses[issue.status]}</span></div><p className="whitespace-pre-wrap text-sm">{issue.body}</p><p className="text-xs text-muted">协商期限：{new Date(issue.dueAt).toLocaleString('zh-CN',{hour12:false})} · 发起方：{issue.authorId===profile?.id?'你':'合作方'}</p>{data.messages.filter(m=>m.targetId===issue.id).map(m=><div className="rounded-lg bg-canvas p-3" key={m.id}><p className="text-xs text-muted">{m.authorId===profile?.id?'你':'合作方 / 管理员'} · {new Date(m.createdAt).toLocaleString('zh-CN',{hour12:false})}</p><p className="mt-1 whitespace-pre-wrap text-sm">{m.body}</p>{m.evidence.map(e=><a className="mr-3 text-xs text-cyan" href={e.uri} target="_blank" rel="noreferrer" key={e.uri}>{e.label}</a>)}</div>)}{issue.resolution&&<p className="rounded-lg bg-lime/10 p-3 text-sm">处理结论：{issue.resolution}</p>}{issue.status!=='resolved'&&<><textarea aria-label={`回应 ${issue.title}`} className="field min-h-20" placeholder="补充事实、交付证据链接或处理结论…" value={responses[issue.id]??''} maxLength={2000} onChange={e=>setResponses({...responses,[issue.id]:e.target.value})}/><div className="flex flex-wrap gap-2"><button className="btn-secondary" disabled={busy||(responses[issue.id]?.trim().length??0)<5} onClick={()=>void act(`issues/${issue.id}/respond`,{body:responses[issue.id]},()=>setResponses({...responses,[issue.id]:''}))}>补充回应</button>{issue.status==='open'&&<button className="btn-secondary" disabled={busy||(Date.now()<Date.parse(issue.dueAt)&&profile?.role!=='admin')} onClick={()=>void act(`issues/${issue.id}/escalate`,{})}>申请协调 / 仲裁审核</button>}{(issue.authorId===profile?.id||profile?.role==='admin')&&<button className="btn-secondary" disabled={busy||(responses[issue.id]?.trim().length??0)<12} onClick={()=>void act(`issues/${issue.id}/resolve`,{body:responses[issue.id]})}>以此结论关闭</button>}</div></>}</article>)}
      <div className="border-t border-line pt-5"><h3 className="font-semibold">七天双盲互评</h3><p className="mt-2 text-xs leading-5 text-muted">双方提交或结案后七天到期再公开；提交后不可修改，可在公开后回应。同一任务中每个开发者只评价任务方一次。退款 / 取消任务的评价保留记录，不计入信誉。{data.reviewEndsAt?` 截止：${new Date(data.reviewEndsAt).toLocaleString('zh-CN',{hour12:false})}。`:' 任务结案后开放。'}</p>
      {pair&&data.canReview&&!pair.submitted?<form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();void act('reviews',{developerId,ratings,comment},()=>setComment(''));}}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(data.role==='developer'?developerLabels:requesterLabels).map((label,index)=><label key={label}><span className="field-label">{label}</span><select className="field" value={ratings[index]} onChange={e=>setRatings(ratings.map((v,i)=>i===index?Number(e.target.value):v))}>{[5,4,3,2,1].map(v=><option value={v} key={v}>{v} / 5</option>)}</select></label>)}</div><label className="block"><span className="field-label">合作评价（公开后可见）</span><textarea className="field min-h-24" required minLength={5} maxLength={1000} value={comment} onChange={e=>setComment(e.target.value)}/></label><button className="btn-primary" type="submit" disabled={busy}>{busy&&<LoaderCircle size={14} className="animate-spin"/>}密封提交评价</button></form>:pair?.submitted?<p className="mt-3 text-sm text-cyan">你的评价已提交。{pair.counterpartSubmitted?'双方已提交，评价已公开。':'等待对方提交或窗口到期。'}</p>:null}
      <div className="mt-4 space-y-3">{data.reviews.filter(r=>!developerId||r.developerId===developerId).map(review=><article key={review.id} className="space-y-2 rounded-xl bg-canvas p-4"><p className="text-xs text-muted">{review.direction==='requester'?'任务方评价交付':'开发者评价合作'} · {review.publishedAt?'已公开':'仅你可见 · 密封中'} · {review.eligible?'正常结算':'不计信誉'} · {review.caseStatus==='refunded'?'已退款':review.caseStatus==='cancelled'?'已取消':review.caseStatus==='disputed'?'有争议':'已结算'}</p><p className="text-sm">{(review.ratings.reduce((a,b)=>a+b,0)/5).toFixed(1)} / 5</p><p className="whitespace-pre-wrap text-sm">{review.comment}</p>{data.messages.filter(m=>m.targetId===review.id).map(m=><p key={m.id} className="border-l-2 border-line pl-3 text-sm">{m.authorId===profile?.id?'你的回应':'对方回应'}：{m.body}</p>)}{review.publishedAt&&data.role!=='observer'&&<div className="flex flex-col gap-2 sm:flex-row"><input aria-label="回应评价" className="field" placeholder="回应会公开展示；争议可通过上方评价复核提交" maxLength={2000} value={responses[review.id]??''} onChange={e=>setResponses({...responses,[review.id]:e.target.value})}/><button className="btn-secondary shrink-0" disabled={busy||(responses[review.id]?.trim().length??0)<5} onClick={()=>void act(`reviews/${review.id}/respond`,{body:responses[review.id]},()=>setResponses({...responses,[review.id]:''}))}>回应评价</button></div>}</article>)}</div></div>
    </>}
  </section>;
}
